project_id = "pzzzcxspasbswpxzdqku"

[functions.process-payment]
verify_jwt = false

[functions.accept-hosted-token]
verify_jwt = false

[functions.authorize-webhook]
verify_jwt = false

[functions.get-auth-config]
verify_jwt = false

[functions.generate-sim-form]
verify_jwt = false