project_id = "pzzzcxspasbswpxzdqku"

[functions.process-payment]
verify_jwt = false

[functions.accept-hosted-token]
verify_jwt = false

[functions.accept-hosted-return]
verify_jwt = false

[functions.authorize-webhook]
verify_jwt = false

[functions.get-auth-config]
verify_jwt = false

[functions.generate-sim-form]
verify_jwt = false

[functions.create-customer-profile]
verify_jwt = false

[functions.add-payment-profile]
verify_jwt = false

[functions.manage-customer-profile]
verify_jwt = false

[functions.charge-customer-profile]
verify_jwt = false

[functions.get-customer-profile]
verify_jwt = false

[functions.get-hosted-profile-token]
verify_jwt = false
