// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzzzcxspasbswpxzdqku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6enpjeHNwYXNic3dweHpkcWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzUyNzksImV4cCI6MjA3NDA1MTI3OX0.O7gtP62CKjKicgZqf0Xx3T5m9MGlVPVVt0wXG80pjsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});